version: '3'
services:
  redis:
    image: "redis:alpine"
    container_name: inv_redis
    ports:
      - "6379:6379"
  rabbitmq:
    image: rabbitmq:3.7
    container_name: inv_queue
    ports:
      - "5672:5672"
  api:
    container_name: inv_api
    build: ./
    ports:
      - "8082:8080"
    depends_on:
      - redis
      - rabbitmq
    links:
      - redis
      - rabbitmq
    volumes:
      - ./:/home/app
    command: [ "npm", "start" ]