version: '2'
services:  
  node:
    image: "node:12"
    user: "node"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=production
    volumes:
      - ./:/home/app
    expose:
      - "3000"
    command: [npm start]