version: '2'
services:  
  web:
    image: "node:12"
    name: "demo_inventory"
    user: "admin"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=production
    volumes:
      - ./:/home/app
    expose:
      - "8080:8080"
    command: []